# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 508)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(740, 508))
        Form.setMaximumSize(QtCore.QSize(740, 600))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(9)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 420, 721, 72))
        self.textBrowser.setMinimumSize(QtCore.QSize(721, 71))
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_22 = QtWidgets.QGroupBox(Form)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 0, 721, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setTitle("")
        self.groupBox_22.setCheckable(False)
        self.groupBox_22.setObjectName("groupBox_22")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_22)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 721, 381))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 701, 331))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.tabWidget.addTab(self.tab_2, "")
        self.Dosing_tab = QtWidgets.QWidget()
        self.Dosing_tab.setObjectName("Dosing_tab")
        self.Auto_Dosing_Options = QtWidgets.QGroupBox(self.Dosing_tab)
        self.Auto_Dosing_Options.setGeometry(QtCore.QRect(9, 9, 451, 351))
        self.Auto_Dosing_Options.setAutoFillBackground(True)
        self.Auto_Dosing_Options.setObjectName("Auto_Dosing_Options")
        self.groupBox_9 = QtWidgets.QGroupBox(self.Auto_Dosing_Options)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 23, 431, 41))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar.setProperty("value", 69)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Auto_Dosing_Options)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 70, 441, 131))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 0, 171, 131))
        self.groupBox_13.setAutoFillBackground(False)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.feed_sec_label = QtWidgets.QLabel(self.groupBox_13)
        self.feed_sec_label.setObjectName("feed_sec_label")
        self.gridLayout_8.addWidget(self.feed_sec_label, 1, 1, 1, 1)
        self.feed_next_dose_label = QtWidgets.QLabel(self.groupBox_13)
        self.feed_next_dose_label.setObjectName("feed_next_dose_label")
        self.gridLayout_8.addWidget(self.feed_next_dose_label, 3, 0, 1, 2)
        self.feed_week_label = QtWidgets.QLabel(self.groupBox_13)
        self.feed_week_label.setObjectName("feed_week_label")
        self.gridLayout_8.addWidget(self.feed_week_label, 2, 1, 1, 1)
        self.feed_comboBox_2 = QtWidgets.QComboBox(self.groupBox_13)
        self.feed_comboBox_2.setObjectName("feed_comboBox_2")
        self.feed_comboBox_2.addItem("")
        self.feed_comboBox_2.addItem("")
        self.feed_comboBox_2.addItem("")
        self.feed_comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.feed_comboBox_2, 2, 0, 1, 1)
        self.feed_timeEdit = QtWidgets.QTimeEdit(self.groupBox_13)
        self.feed_timeEdit.setObjectName("feed_timeEdit")
        self.gridLayout_8.addWidget(self.feed_timeEdit, 1, 0, 1, 1)
        self.feed_pushButton = QtWidgets.QPushButton(self.groupBox_13)
        self.feed_pushButton.setObjectName("feed_pushButton")
        self.gridLayout_8.addWidget(self.feed_pushButton, 0, 0, 1, 2)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_14.setGeometry(QtCore.QRect(270, 0, 171, 131))
        self.groupBox_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_14.setAutoFillBackground(False)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.c02_ml_outLcd = QtWidgets.QLCDNumber(self.groupBox_14)
        self.c02_ml_outLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.c02_ml_outLcd.setObjectName("c02_ml_outLcd")
        self.gridLayout_10.addWidget(self.c02_ml_outLcd, 2, 0, 1, 2)
        self.c02_comboBox_2 = QtWidgets.QComboBox(self.groupBox_14)
        self.c02_comboBox_2.setObjectName("c02_comboBox_2")
        self.c02_comboBox_2.addItem("")
        self.c02_comboBox_2.addItem("")
        self.c02_comboBox_2.addItem("")
        self.c02_comboBox_2.addItem("")
        self.gridLayout_10.addWidget(self.c02_comboBox_2, 3, 0, 1, 1)
        self.c02_pushButton = QtWidgets.QPushButton(self.groupBox_14)
        self.c02_pushButton.setObjectName("c02_pushButton")
        self.gridLayout_10.addWidget(self.c02_pushButton, 0, 0, 1, 3)
        self.c02_week_label = QtWidgets.QLabel(self.groupBox_14)
        self.c02_week_label.setObjectName("c02_week_label")
        self.gridLayout_10.addWidget(self.c02_week_label, 3, 1, 1, 2)
        self.c02_next_dose_label = QtWidgets.QLabel(self.groupBox_14)
        self.c02_next_dose_label.setObjectName("c02_next_dose_label")
        self.gridLayout_10.addWidget(self.c02_next_dose_label, 4, 0, 1, 3)
        self.c02_ml_label = QtWidgets.QLabel(self.groupBox_14)
        self.c02_ml_label.setObjectName("c02_ml_label")
        self.gridLayout_10.addWidget(self.c02_ml_label, 2, 2, 1, 1)
        self.co2_seconds_display = QtWidgets.QLCDNumber(self.groupBox_14)
        self.co2_seconds_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.co2_seconds_display.setObjectName("co2_seconds_display")
        self.gridLayout_10.addWidget(self.co2_seconds_display, 1, 0, 1, 2)
        self.c02_seconds_label_2 = QtWidgets.QLabel(self.groupBox_14)
        self.c02_seconds_label_2.setObjectName("c02_seconds_label_2")
        self.gridLayout_10.addWidget(self.c02_seconds_label_2, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.Auto_Dosing_Options)
        self.line.setGeometry(QtCore.QRect(0, 200, 441, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Auto_Dosing_Options)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 210, 441, 131))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 0, 171, 131))
        self.groupBox_15.setAutoFillBackground(False)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fertz_ml_display = QtWidgets.QLCDNumber(self.groupBox_15)
        self.fertz_ml_display.setMinimumSize(QtCore.QSize(0, 25))
        self.fertz_ml_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.fertz_ml_display.setObjectName("fertz_ml_display")
        self.gridLayout_3.addWidget(self.fertz_ml_display, 1, 0, 1, 2)
        self.fertz_ml_label = QtWidgets.QLabel(self.groupBox_15)
        self.fertz_ml_label.setObjectName("fertz_ml_label")
        self.gridLayout_3.addWidget(self.fertz_ml_label, 1, 2, 1, 1)
        self.fertz_comboBox_2 = QtWidgets.QComboBox(self.groupBox_15)
        self.fertz_comboBox_2.setObjectName("fertz_comboBox_2")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.fertz_comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.fertz_comboBox_2, 2, 0, 2, 1)
        self.fertz_week_label = QtWidgets.QLabel(self.groupBox_15)
        self.fertz_week_label.setObjectName("fertz_week_label")
        self.gridLayout_3.addWidget(self.fertz_week_label, 3, 1, 1, 2)
        self.fertz_next_dose_label = QtWidgets.QLabel(self.groupBox_15)
        self.fertz_next_dose_label.setAutoFillBackground(False)
        self.fertz_next_dose_label.setObjectName("fertz_next_dose_label")
        self.gridLayout_3.addWidget(self.fertz_next_dose_label, 4, 0, 1, 3)
        self.fertz_pushButton = QtWidgets.QPushButton(self.groupBox_15)
        self.fertz_pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fertz_pushButton.setObjectName("fertz_pushButton")
        self.gridLayout_3.addWidget(self.fertz_pushButton, 0, 0, 1, 3)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_16.setGeometry(QtCore.QRect(270, 0, 171, 131))
        self.groupBox_16.setAutoFillBackground(False)
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tapSafe_pushButton = QtWidgets.QPushButton(self.groupBox_16)
        self.tapSafe_pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tapSafe_pushButton.setObjectName("tapSafe_pushButton")
        self.gridLayout_11.addWidget(self.tapSafe_pushButton, 0, 0, 1, 3)
        self.water_conditioner_ml_display = QtWidgets.QLCDNumber(self.groupBox_16)
        self.water_conditioner_ml_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.water_conditioner_ml_display.setObjectName("water_conditioner_ml_display")
        self.gridLayout_11.addWidget(self.water_conditioner_ml_display, 1, 0, 1, 2)
        self.tapSafe_ml_label = QtWidgets.QLabel(self.groupBox_16)
        self.tapSafe_ml_label.setObjectName("tapSafe_ml_label")
        self.gridLayout_11.addWidget(self.tapSafe_ml_label, 1, 2, 1, 1)
        self.water_conditioner_comboBox = QtWidgets.QComboBox(self.groupBox_16)
        self.water_conditioner_comboBox.setObjectName("water_conditioner_comboBox")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.water_conditioner_comboBox.addItem("")
        self.gridLayout_11.addWidget(self.water_conditioner_comboBox, 2, 0, 1, 1)
        self.tapSafe_week_label = QtWidgets.QLabel(self.groupBox_16)
        self.tapSafe_week_label.setObjectName("tapSafe_week_label")
        self.gridLayout_11.addWidget(self.tapSafe_week_label, 2, 1, 1, 2)
        self.tapSafe_next_dose_label = QtWidgets.QLabel(self.groupBox_16)
        self.tapSafe_next_dose_label.setObjectName("tapSafe_next_dose_label")
        self.gridLayout_11.addWidget(self.tapSafe_next_dose_label, 3, 0, 1, 3)
        self.Auto_Dosing = QtWidgets.QGroupBox(self.Dosing_tab)
        self.Auto_Dosing.setGeometry(QtCore.QRect(476, 9, 231, 341))
        self.Auto_Dosing.setAutoFillBackground(True)
        self.Auto_Dosing.setObjectName("Auto_Dosing")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.Auto_Dosing)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Auto_Dosing)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 4, 2, 1, 1)
        self.feed_outLcd = QtWidgets.QLCDNumber(self.groupBox_5)
        self.feed_outLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.feed_outLcd.setObjectName("feed_outLcd")
        self.gridLayout_9.addWidget(self.feed_outLcd, 3, 0, 1, 1)
        self.c02_label = QtWidgets.QLabel(self.groupBox_5)
        self.c02_label.setObjectName("c02_label")
        self.gridLayout_9.addWidget(self.c02_label, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.FeedCalibrationButton = QtWidgets.QPushButton(self.groupBox_5)
        self.FeedCalibrationButton.setObjectName("FeedCalibrationButton")
        self.gridLayout_9.addWidget(self.FeedCalibrationButton, 4, 0, 1, 1)
        self.co2_dosing_lcd = QtWidgets.QLCDNumber(self.groupBox_5)
        self.co2_dosing_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.co2_dosing_lcd.setObjectName("co2_dosing_lcd")
        self.gridLayout_9.addWidget(self.co2_dosing_lcd, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 2, 1, 1)
        self.feed_label = QtWidgets.QLabel(self.groupBox_5)
        self.feed_label.setObjectName("feed_label")
        self.gridLayout_9.addWidget(self.feed_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.c02_comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.c02_comboBox.setObjectName("c02_comboBox")
        self.c02_comboBox.addItem("")
        self.c02_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.c02_comboBox, 6, 1, 1, 1)
        self.C02CalibrationButton = QtWidgets.QPushButton(self.groupBox_5)
        self.C02CalibrationButton.setObjectName("C02CalibrationButton")
        self.gridLayout_9.addWidget(self.C02CalibrationButton, 4, 1, 1, 1)
        self.feed_comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.feed_comboBox.setObjectName("feed_comboBox")
        self.feed_comboBox.addItem("")
        self.feed_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.feed_comboBox, 6, 0, 1, 1)
        self.co2_calibration_perml_display = QtWidgets.QLCDNumber(self.groupBox_5)
        self.co2_calibration_perml_display.setSmallDecimalPoint(False)
        self.co2_calibration_perml_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.co2_calibration_perml_display.setObjectName("co2_calibration_perml_display")
        self.gridLayout_9.addWidget(self.co2_calibration_perml_display, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 7, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Auto_Dosing)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_13.addWidget(self.line_2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Auto_Dosing)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.conditioner_dosing_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.conditioner_dosing_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.conditioner_dosing_lcd.setObjectName("conditioner_dosing_lcd")
        self.gridLayout_7.addWidget(self.conditioner_dosing_lcd, 1, 1, 1, 1)
        self.fertz_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.fertz_comboBox.setObjectName("fertz_comboBox")
        self.fertz_comboBox.addItem("")
        self.fertz_comboBox.addItem("")
        self.gridLayout_7.addWidget(self.fertz_comboBox, 3, 0, 1, 1)
        self.fertz_label = QtWidgets.QLabel(self.groupBox_3)
        self.fertz_label.setObjectName("fertz_label")
        self.gridLayout_7.addWidget(self.fertz_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tapSafe_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.tapSafe_comboBox.setObjectName("tapSafe_comboBox")
        self.tapSafe_comboBox.addItem("")
        self.tapSafe_comboBox.addItem("")
        self.gridLayout_7.addWidget(self.tapSafe_comboBox, 3, 1, 1, 1)
        self.TapSafeCalibrationButton = QtWidgets.QPushButton(self.groupBox_3)
        self.TapSafeCalibrationButton.setObjectName("TapSafeCalibrationButton")
        self.gridLayout_7.addWidget(self.TapSafeCalibrationButton, 2, 1, 1, 1)
        self.FertzCalibrationButton = QtWidgets.QPushButton(self.groupBox_3)
        self.FertzCalibrationButton.setObjectName("FertzCalibrationButton")
        self.gridLayout_7.addWidget(self.FertzCalibrationButton, 2, 0, 1, 1)
        self.tapSafe_label = QtWidgets.QLabel(self.groupBox_3)
        self.tapSafe_label.setObjectName("tapSafe_label")
        self.gridLayout_7.addWidget(self.tapSafe_label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.fertz_dosing_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.fertz_dosing_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.fertz_dosing_lcd.setObjectName("fertz_dosing_lcd")
        self.gridLayout_7.addWidget(self.fertz_dosing_lcd, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.Dosing_tab, "")
        self.Home_tab = QtWidgets.QWidget()
        self.Home_tab.setObjectName("Home_tab")
        self.Light_Modes = QtWidgets.QGroupBox(self.Home_tab)
        self.Light_Modes.setGeometry(QtCore.QRect(9, 9, 121, 191))
        self.Light_Modes.setAutoFillBackground(True)
        self.Light_Modes.setCheckable(True)
        self.Light_Modes.setChecked(False)
        self.Light_Modes.setObjectName("Light_Modes")
        self.sunrise_sunset_radioButton = QtWidgets.QRadioButton(self.Light_Modes)
        self.sunrise_sunset_radioButton.setGeometry(QtCore.QRect(10, 23, 95, 17))
        self.sunrise_sunset_radioButton.setAutoRepeat(False)
        self.sunrise_sunset_radioButton.setObjectName("sunrise_sunset_radioButton")
        self.manual_hour_mode_radioButton = QtWidgets.QRadioButton(self.Light_Modes)
        self.manual_hour_mode_radioButton.setGeometry(QtCore.QRect(10, 46, 88, 17))
        self.manual_hour_mode_radioButton.setObjectName("manual_hour_mode_radioButton")
        self.toggle_mode_radioButton = QtWidgets.QRadioButton(self.Light_Modes)
        self.toggle_mode_radioButton.setGeometry(QtCore.QRect(10, 69, 91, 17))
        self.toggle_mode_radioButton.setObjectName("toggle_mode_radioButton")
        self.light_clock_display = QtWidgets.QLCDNumber(self.Light_Modes)
        self.light_clock_display.setGeometry(QtCore.QRect(10, 150, 91, 31))
        self.light_clock_display.setObjectName("light_clock_display")
        self.light_mode_comboBox = QtWidgets.QComboBox(self.Light_Modes)
        self.light_mode_comboBox.setGeometry(QtCore.QRect(10, 120, 51, 22))
        self.light_mode_comboBox.setObjectName("light_mode_comboBox")
        self.light_mode_comboBox.addItem("")
        self.light_mode_comboBox.addItem("")
        self.light_mode_comboBox.addItem("")
        self.light_mode_display = QtWidgets.QLineEdit(self.Light_Modes)
        self.light_mode_display.setGeometry(QtCore.QRect(10, 90, 101, 20))
        self.light_mode_display.setObjectName("light_mode_display")
        self.Light_Modes_Manual_Hours = QtWidgets.QGroupBox(self.Home_tab)
        self.Light_Modes_Manual_Hours.setGeometry(QtCore.QRect(140, 10, 571, 331))
        self.Light_Modes_Manual_Hours.setAutoFillBackground(True)
        self.Light_Modes_Manual_Hours.setObjectName("Light_Modes_Manual_Hours")
        self.pushButton_7 = QtWidgets.QPushButton(self.Light_Modes_Manual_Hours)
        self.pushButton_7.setGeometry(QtCore.QRect(490, 15, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_21 = QtWidgets.QGroupBox(self.Light_Modes_Manual_Hours)
        self.groupBox_21.setGeometry(QtCore.QRect(419, 40, 151, 159))
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.off_hour_wheel = QtWidgets.QDial(self.groupBox_21)
        self.off_hour_wheel.setMaximum(1440)
        self.off_hour_wheel.setProperty("value", 720)
        self.off_hour_wheel.setWrapping(True)
        self.off_hour_wheel.setNotchTarget(24.0)
        self.off_hour_wheel.setNotchesVisible(True)
        self.off_hour_wheel.setObjectName("off_hour_wheel")
        self.verticalLayout_3.addWidget(self.off_hour_wheel)
        self.off_hour_timeEdit = QtWidgets.QTimeEdit(self.groupBox_21)
        self.off_hour_timeEdit.setWrapping(True)
        self.off_hour_timeEdit.setAccelerated(True)
        self.off_hour_timeEdit.setObjectName("off_hour_timeEdit")
        self.verticalLayout_3.addWidget(self.off_hour_timeEdit)
        self.groupBox_19 = QtWidgets.QGroupBox(self.Light_Modes_Manual_Hours)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 40, 151, 159))
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout.setObjectName("verticalLayout")
        self.day_hour_wheel = QtWidgets.QDial(self.groupBox_19)
        self.day_hour_wheel.setAutoFillBackground(False)
        self.day_hour_wheel.setMaximum(1440)
        self.day_hour_wheel.setProperty("value", 720)
        self.day_hour_wheel.setWrapping(True)
        self.day_hour_wheel.setNotchTarget(24.0)
        self.day_hour_wheel.setNotchesVisible(True)
        self.day_hour_wheel.setObjectName("day_hour_wheel")
        self.verticalLayout.addWidget(self.day_hour_wheel)
        self.day_hour_timeEdit = QtWidgets.QTimeEdit(self.groupBox_19)
        self.day_hour_timeEdit.setWrapping(True)
        self.day_hour_timeEdit.setAccelerated(True)
        self.day_hour_timeEdit.setObjectName("day_hour_timeEdit")
        self.verticalLayout.addWidget(self.day_hour_timeEdit)
        self.groupBox_20 = QtWidgets.QGroupBox(self.Light_Modes_Manual_Hours)
        self.groupBox_20.setGeometry(QtCore.QRect(210, 40, 151, 159))
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.night_hour_wheel = QtWidgets.QDial(self.groupBox_20)
        self.night_hour_wheel.setMaximum(1440)
        self.night_hour_wheel.setProperty("value", 720)
        self.night_hour_wheel.setWrapping(True)
        self.night_hour_wheel.setNotchTarget(24.0)
        self.night_hour_wheel.setNotchesVisible(True)
        self.night_hour_wheel.setObjectName("night_hour_wheel")
        self.verticalLayout_2.addWidget(self.night_hour_wheel)
        self.night_hour_timeEdit = QtWidgets.QTimeEdit(self.groupBox_20)
        self.night_hour_timeEdit.setWrapping(True)
        self.night_hour_timeEdit.setAccelerated(True)
        self.night_hour_timeEdit.setObjectName("night_hour_timeEdit")
        self.verticalLayout_2.addWidget(self.night_hour_timeEdit)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Home_tab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 210, 120, 131))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.tabWidget.addTab(self.Home_tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_23.setGeometry(QtCore.QRect(10, -10, 701, 421))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_24.setGeometry(QtCore.QRect(0, 20, 351, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setTitle("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.groupBox_24)
        self.calendarWidget_2.setGeometry(QtCore.QRect(10, 10, 312, 183))
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_25.setGeometry(QtCore.QRect(350, 20, 351, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_25.sizePolicy().hasHeightForWidth())
        self.groupBox_25.setSizePolicy(sizePolicy)
        self.groupBox_25.setTitle("")
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 0, 331, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_26.sizePolicy().hasHeightForWidth())
        self.groupBox_26.setSizePolicy(sizePolicy)
        self.groupBox_26.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_26)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hours_22 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_22.setCheckable(True)
        self.hours_22.setAutoDefault(True)
        self.hours_22.setObjectName("hours_22")
        self.gridLayout_5.addWidget(self.hours_22, 3, 5, 1, 1)
        self.hours_21 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_21.setCheckable(True)
        self.hours_21.setAutoDefault(True)
        self.hours_21.setObjectName("hours_21")
        self.gridLayout_5.addWidget(self.hours_21, 3, 4, 1, 1)
        self.hours_5 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_5.setCheckable(True)
        self.hours_5.setAutoDefault(True)
        self.hours_5.setObjectName("hours_5")
        self.gridLayout_5.addWidget(self.hours_5, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_26)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.hours_0 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_0.setCheckable(True)
        self.hours_0.setAutoDefault(True)
        self.hours_0.setObjectName("hours_0")
        self.gridLayout_5.addWidget(self.hours_0, 0, 1, 1, 1)
        self.hours_20 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_20.setCheckable(True)
        self.hours_20.setAutoDefault(True)
        self.hours_20.setFlat(False)
        self.hours_20.setObjectName("hours_20")
        self.gridLayout_5.addWidget(self.hours_20, 3, 3, 1, 1)
        self.hours_1 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_1.setCheckable(True)
        self.hours_1.setAutoDefault(True)
        self.hours_1.setObjectName("hours_1")
        self.gridLayout_5.addWidget(self.hours_1, 0, 2, 1, 1)
        self.hours_23 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_23.setCheckable(True)
        self.hours_23.setAutoDefault(True)
        self.hours_23.setObjectName("hours_23")
        self.gridLayout_5.addWidget(self.hours_23, 3, 6, 1, 1)
        self.hours_14 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_14.setCheckable(True)
        self.hours_14.setAutoDefault(True)
        self.hours_14.setObjectName("hours_14")
        self.gridLayout_5.addWidget(self.hours_14, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_26)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)
        self.hours_10 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_10.setCheckable(True)
        self.hours_10.setAutoDefault(True)
        self.hours_10.setObjectName("hours_10")
        self.gridLayout_5.addWidget(self.hours_10, 1, 5, 1, 1)
        self.hours_18 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_18.setStyleSheet("")
        self.hours_18.setCheckable(True)
        self.hours_18.setAutoDefault(True)
        self.hours_18.setObjectName("hours_18")
        self.gridLayout_5.addWidget(self.hours_18, 3, 1, 1, 1)
        self.hours_3 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_3.setCheckable(True)
        self.hours_3.setAutoDefault(True)
        self.hours_3.setObjectName("hours_3")
        self.gridLayout_5.addWidget(self.hours_3, 0, 4, 1, 1)
        self.hours_16 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_16.setCheckable(True)
        self.hours_16.setAutoDefault(True)
        self.hours_16.setObjectName("hours_16")
        self.gridLayout_5.addWidget(self.hours_16, 2, 5, 1, 1)
        self.hours_9 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_9.setCheckable(True)
        self.hours_9.setAutoDefault(True)
        self.hours_9.setObjectName("hours_9")
        self.gridLayout_5.addWidget(self.hours_9, 1, 4, 1, 1)
        self.hours_7 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_7.setCheckable(True)
        self.hours_7.setAutoDefault(True)
        self.hours_7.setObjectName("hours_7")
        self.gridLayout_5.addWidget(self.hours_7, 1, 2, 1, 1)
        self.hours_11 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_11.setCheckable(True)
        self.hours_11.setAutoDefault(True)
        self.hours_11.setObjectName("hours_11")
        self.gridLayout_5.addWidget(self.hours_11, 1, 6, 1, 1)
        self.hours_13 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_13.setCheckable(True)
        self.hours_13.setAutoDefault(True)
        self.hours_13.setDefault(False)
        self.hours_13.setFlat(False)
        self.hours_13.setObjectName("hours_13")
        self.gridLayout_5.addWidget(self.hours_13, 2, 2, 1, 1)
        self.hours_6 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_6.setCheckable(True)
        self.hours_6.setAutoDefault(True)
        self.hours_6.setObjectName("hours_6")
        self.gridLayout_5.addWidget(self.hours_6, 1, 1, 1, 1)
        self.hours_12 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_12.setCheckable(True)
        self.hours_12.setAutoDefault(True)
        self.hours_12.setObjectName("hours_12")
        self.gridLayout_5.addWidget(self.hours_12, 2, 1, 1, 1)
        self.hours_8 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_8.setCheckable(True)
        self.hours_8.setAutoDefault(True)
        self.hours_8.setObjectName("hours_8")
        self.gridLayout_5.addWidget(self.hours_8, 1, 3, 1, 1)
        self.hours_2 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_2.setCheckable(True)
        self.hours_2.setAutoDefault(True)
        self.hours_2.setObjectName("hours_2")
        self.gridLayout_5.addWidget(self.hours_2, 0, 3, 1, 1)
        self.hours_17 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_17.setCheckable(True)
        self.hours_17.setAutoDefault(True)
        self.hours_17.setObjectName("hours_17")
        self.gridLayout_5.addWidget(self.hours_17, 2, 6, 1, 1)
        self.hours_15 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_15.setCheckable(True)
        self.hours_15.setAutoDefault(True)
        self.hours_15.setObjectName("hours_15")
        self.gridLayout_5.addWidget(self.hours_15, 2, 4, 1, 1)
        self.hours_4 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_4.setCheckable(True)
        self.hours_4.setAutoDefault(True)
        self.hours_4.setObjectName("hours_4")
        self.gridLayout_5.addWidget(self.hours_4, 0, 5, 1, 1)
        self.hours_19 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_19.setCheckable(True)
        self.hours_19.setAutoDefault(True)
        self.hours_19.setObjectName("hours_19")
        self.gridLayout_5.addWidget(self.hours_19, 3, 2, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_27.sizePolicy().hasHeightForWidth())
        self.groupBox_27.setSizePolicy(sizePolicy)
        self.groupBox_27.setTitle("")
        self.groupBox_27.setFlat(False)
        self.groupBox_27.setObjectName("groupBox_27")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_27)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hour_comboBox = QtWidgets.QComboBox(self.groupBox_27)
        self.hour_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.hour_comboBox.setObjectName("hour_comboBox")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.hour_comboBox)
        self.hour_clear = QtWidgets.QPushButton(self.groupBox_27)
        self.hour_clear.setObjectName("hour_clear")
        self.horizontalLayout_2.addWidget(self.hour_clear)
        self.hour_save_button = QtWidgets.QPushButton(self.groupBox_27)
        self.hour_save_button.setObjectName("hour_save_button")
        self.horizontalLayout_2.addWidget(self.hour_save_button)
        self.gridLayout_5.addWidget(self.groupBox_27, 4, 0, 1, 7)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 10, 691, 341))
        self.groupBox_17.setAutoFillBackground(False)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 691, 121))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.inlet_level_progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.inlet_level_progressBar.setGeometry(QtCore.QRect(100, 60, 471, 21))
        self.inlet_level_progressBar.setProperty("value", 24)
        self.inlet_level_progressBar.setObjectName("inlet_level_progressBar")
        self.inlet_level_label = QtWidgets.QLabel(self.groupBox)
        self.inlet_level_label.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.inlet_level_label.setObjectName("inlet_level_label")
        self.aquarium_level_progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.aquarium_level_progressBar.setGeometry(QtCore.QRect(100, 30, 471, 21))
        self.aquarium_level_progressBar.setProperty("value", 24)
        self.aquarium_level_progressBar.setObjectName("aquarium_level_progressBar")
        self.outlet_level_progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.outlet_level_progressBar.setGeometry(QtCore.QRect(100, 90, 471, 21))
        self.outlet_level_progressBar.setProperty("value", 24)
        self.outlet_level_progressBar.setObjectName("outlet_level_progressBar")
        self.outlet_level_label = QtWidgets.QLabel(self.groupBox)
        self.outlet_level_label.setGeometry(QtCore.QRect(10, 90, 84, 21))
        self.outlet_level_label.setObjectName("outlet_level_label")
        self.aquarium_level_label = QtWidgets.QLabel(self.groupBox)
        self.aquarium_level_label.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.aquarium_level_label.setTextFormat(QtCore.Qt.AutoText)
        self.aquarium_level_label.setScaledContents(True)
        self.aquarium_level_label.setWordWrap(False)
        self.aquarium_level_label.setObjectName("aquarium_level_label")
        self.water_cycle_button = QtWidgets.QPushButton(self.groupBox)
        self.water_cycle_button.setGeometry(QtCore.QRect(570, 30, 104, 21))
        self.water_cycle_button.setObjectName("water_cycle_button")
        self.percentage_of_tank_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.percentage_of_tank_comboBox.setGeometry(QtCore.QRect(570, 60, 104, 21))
        self.percentage_of_tank_comboBox.setObjectName("percentage_of_tank_comboBox")
        self.percentage_of_tank_comboBox.addItem("")
        self.percentage_of_tank_comboBox.addItem("")
        self.percentage_of_tank_comboBox.addItem("")
        self.percentage_of_tank_comboBox.addItem("")
        self.percentage_of_tank_comboBox.addItem("")
        self.percentage_of_tank_comboBox.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(570, 90, 104, 21))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.label_10.setObjectName("label_10")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 120, 381, 221))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 111, 23))
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pump_in_button = QtWidgets.QPushButton(self.groupBox_18)
        self.pump_in_button.setGeometry(QtCore.QRect(130, 40, 111, 23))
        self.pump_in_button.setObjectName("pump_in_button")
        self.pump_out_button = QtWidgets.QPushButton(self.groupBox_18)
        self.pump_out_button.setGeometry(QtCore.QRect(130, 90, 111, 23))
        self.pump_out_button.setObjectName("pump_out_button")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 40, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 90, 111, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_29.setGeometry(QtCore.QRect(200, 120, 171, 101))
        self.groupBox_29.setTitle("")
        self.groupBox_29.setObjectName("groupBox_29")
        self.ht_alert_edit = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.ht_alert_edit.setGeometry(QtCore.QRect(100, 10, 62, 22))
        self.ht_alert_edit.setObjectName("ht_alert_edit")
        self.lt_alert_edit = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.lt_alert_edit.setGeometry(QtCore.QRect(100, 50, 62, 22))
        self.lt_alert_edit.setObjectName("lt_alert_edit")
        self.label_18 = QtWidgets.QLabel(self.groupBox_29)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.groupBox_29)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_20.setObjectName("label_20")
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_28.setGeometry(QtCore.QRect(380, 120, 311, 111))
        self.groupBox_28.setTitle("")
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.degrees_c_label = QtWidgets.QLabel(self.groupBox_28)
        self.degrees_c_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.degrees_c_label.setObjectName("degrees_c_label")
        self.gridLayout_6.addWidget(self.degrees_c_label, 0, 2, 1, 1)
        self.tank_degrees_c_display = QtWidgets.QLCDNumber(self.groupBox_28)
        self.tank_degrees_c_display.setObjectName("tank_degrees_c_display")
        self.gridLayout_6.addWidget(self.tank_degrees_c_display, 0, 1, 1, 1)
        self.tank_degrees_f_display = QtWidgets.QLCDNumber(self.groupBox_28)
        self.tank_degrees_f_display.setObjectName("tank_degrees_f_display")
        self.gridLayout_6.addWidget(self.tank_degrees_f_display, 1, 1, 1, 1)
        self.degrees_c_label_2 = QtWidgets.QLabel(self.groupBox_28)
        self.degrees_c_label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.degrees_c_label_2.setObjectName("degrees_c_label_2")
        self.gridLayout_6.addWidget(self.degrees_c_label_2, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 0, 1, 1)
        self.groupBox_30 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_30.setGeometry(QtCore.QRect(380, 230, 311, 111))
        self.groupBox_30.setTitle("")
        self.groupBox_30.setObjectName("groupBox_30")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_30)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.degrees_c_label_3 = QtWidgets.QLabel(self.groupBox_30)
        self.degrees_c_label_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.degrees_c_label_3.setObjectName("degrees_c_label_3")
        self.gridLayout_12.addWidget(self.degrees_c_label_3, 0, 2, 1, 1)
        self.room_degrees_c_display = QtWidgets.QLCDNumber(self.groupBox_30)
        self.room_degrees_c_display.setObjectName("room_degrees_c_display")
        self.gridLayout_12.addWidget(self.room_degrees_c_display, 0, 1, 1, 1)
        self.room_degrees_f_display = QtWidgets.QLCDNumber(self.groupBox_30)
        self.room_degrees_f_display.setObjectName("room_degrees_f_display")
        self.gridLayout_12.addWidget(self.room_degrees_f_display, 1, 1, 1, 1)
        self.degrees_c_label_4 = QtWidgets.QLabel(self.groupBox_30)
        self.degrees_c_label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.degrees_c_label_4.setObjectName("degrees_c_label_4")
        self.gridLayout_12.addWidget(self.degrees_c_label_4, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.Schedule_tab = QtWidgets.QWidget()
        self.Schedule_tab.setObjectName("Schedule_tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Schedule_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 10, 721, 341))
        self.groupBox_7.setObjectName("groupBox_7")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_7)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 23, 501, 321))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(520, 20, 191, 311))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.co2_timeEdit = QtWidgets.QTimeEdit(self.groupBox_8)
        self.co2_timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.co2_timeEdit.setObjectName("co2_timeEdit")
        self.gridLayout_2.addWidget(self.co2_timeEdit, 2, 0, 1, 1)
        self.conditioner__sch_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.conditioner__sch_pushButton.setObjectName("conditioner__sch_pushButton")
        self.gridLayout_2.addWidget(self.conditioner__sch_pushButton, 3, 0, 1, 1)
        self.conditioner_timeEdit = QtWidgets.QTimeEdit(self.groupBox_8)
        self.conditioner_timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conditioner_timeEdit.setObjectName("conditioner_timeEdit")
        self.gridLayout_2.addWidget(self.conditioner_timeEdit, 4, 0, 1, 1)
        self.repeat_comboBox = QtWidgets.QComboBox(self.groupBox_8)
        self.repeat_comboBox.setObjectName("repeat_comboBox")
        self.repeat_comboBox.addItem("")
        self.repeat_comboBox.addItem("")
        self.repeat_comboBox.addItem("")
        self.repeat_comboBox.addItem("")
        self.repeat_comboBox.addItem("")
        self.repeat_comboBox.setItemText(4, "")
        self.gridLayout_2.addWidget(self.repeat_comboBox, 6, 1, 1, 1)
        self.fertz_sch_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.fertz_sch_pushButton.setObjectName("fertz_sch_pushButton")
        self.gridLayout_2.addWidget(self.fertz_sch_pushButton, 1, 1, 1, 1)
        self.co2_sch_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.co2_sch_pushButton.setObjectName("co2_sch_pushButton")
        self.gridLayout_2.addWidget(self.co2_sch_pushButton, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_8)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 7, 0, 1, 2)
        self.water_cycle_timeEdit = QtWidgets.QTimeEdit(self.groupBox_8)
        self.water_cycle_timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.water_cycle_timeEdit.setObjectName("water_cycle_timeEdit")
        self.gridLayout_2.addWidget(self.water_cycle_timeEdit, 4, 1, 1, 1)
        self.fertz_timeEdit = QtWidgets.QTimeEdit(self.groupBox_8)
        self.fertz_timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fertz_timeEdit.setObjectName("fertz_timeEdit")
        self.gridLayout_2.addWidget(self.fertz_timeEdit, 2, 1, 1, 1)
        self.date_display_LineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.date_display_LineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.date_display_LineEdit.setFrame(True)
        self.date_display_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.date_display_LineEdit.setObjectName("date_display_LineEdit")
        self.gridLayout_2.addWidget(self.date_display_LineEdit, 0, 0, 1, 2)
        self.water_cycle_sch_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.water_cycle_sch_pushButton.setObjectName("water_cycle_sch_pushButton")
        self.gridLayout_2.addWidget(self.water_cycle_sch_pushButton, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 1, 1, 1)
        self.del_events_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.del_events_pushButton.setObjectName("del_events_pushButton")
        self.gridLayout_2.addWidget(self.del_events_pushButton, 6, 0, 1, 1)
        self.tabWidget.addTab(self.Schedule_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 0, 681, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TapSafe_Amount_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TapSafe_Amount_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.TapSafe_Amount_label.setObjectName("TapSafe_Amount_label")
        self.gridLayout_4.addWidget(self.TapSafe_Amount_label, 4, 0, 1, 1)
        self.Fertz_outLcd = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.Fertz_outLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Fertz_outLcd.setObjectName("Fertz_outLcd")
        self.gridLayout_4.addWidget(self.Fertz_outLcd, 3, 5, 1, 1)
        self.TapSafe_Equals_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TapSafe_Equals_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.TapSafe_Equals_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TapSafe_Equals_label.setObjectName("TapSafe_Equals_label")
        self.gridLayout_4.addWidget(self.TapSafe_Equals_label, 4, 4, 1, 1)
        self.C02_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.C02_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.C02_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.C02_DoubleSpinBox.setMinimum(1.0)
        self.C02_DoubleSpinBox.setSingleStep(0.01)
        self.C02_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.C02_DoubleSpinBox.setProperty("value", 1.0)
        self.C02_DoubleSpinBox.setObjectName("C02_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.C02_DoubleSpinBox, 1, 1, 1, 1)
        self.C02_to_water_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.C02_to_water_label.setMinimumSize(QtCore.QSize(55, 0))
        self.C02_to_water_label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.C02_to_water_label.setAlignment(QtCore.Qt.AlignCenter)
        self.C02_to_water_label.setObjectName("C02_to_water_label")
        self.gridLayout_4.addWidget(self.C02_to_water_label, 1, 2, 1, 1)
        self.saveDoses_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.saveDoses_pushButton.setObjectName("saveDoses_pushButton")
        self.gridLayout_4.addWidget(self.saveDoses_pushButton, 0, 3, 1, 1)
        self.TapSafe_ml_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TapSafe_ml_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.TapSafe_ml_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TapSafe_ml_label.setObjectName("TapSafe_ml_label")
        self.gridLayout_4.addWidget(self.TapSafe_ml_label, 4, 6, 1, 1)
        self.TankSize_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TankSize_label.setObjectName("TankSize_label")
        self.gridLayout_4.addWidget(self.TankSize_label, 0, 0, 1, 1)
        self.TankSize_DoubleSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.TankSize_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.TankSize_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TankSize_DoubleSpinBox.setAccelerated(True)
        self.TankSize_DoubleSpinBox.setMinimum(1)
        self.TankSize_DoubleSpinBox.setMaximum(999)
        self.TankSize_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.TankSize_DoubleSpinBox.setProperty("value", 1)
        self.TankSize_DoubleSpinBox.setDisplayIntegerBase(10)
        self.TankSize_DoubleSpinBox.setObjectName("TankSize_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.TankSize_DoubleSpinBox, 0, 1, 1, 1)
        self.C02_ml_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.C02_ml_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.C02_ml_label.setAlignment(QtCore.Qt.AlignCenter)
        self.C02_ml_label.setObjectName("C02_ml_label")
        self.gridLayout_4.addWidget(self.C02_ml_label, 1, 6, 1, 1)
        self.TankReq_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TankReq_label.setMinimumSize(QtCore.QSize(0, 0))
        self.TankReq_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TankReq_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TankReq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TankReq_label.setObjectName("TankReq_label")
        self.gridLayout_4.addWidget(self.TankReq_label, 0, 5, 1, 1)
        self.C02_Equals_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.C02_Equals_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.C02_Equals_label.setAlignment(QtCore.Qt.AlignCenter)
        self.C02_Equals_label.setObjectName("C02_Equals_label")
        self.gridLayout_4.addWidget(self.C02_Equals_label, 1, 4, 1, 1)
        self.Fertz_to_water_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Fertz_to_water_label.setMinimumSize(QtCore.QSize(55, 0))
        self.Fertz_to_water_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Fertz_to_water_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Fertz_to_water_label.setObjectName("Fertz_to_water_label")
        self.gridLayout_4.addWidget(self.Fertz_to_water_label, 3, 2, 1, 1)
        self.C02_outLcd = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.C02_outLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.C02_outLcd.setObjectName("C02_outLcd")
        self.gridLayout_4.addWidget(self.C02_outLcd, 1, 5, 1, 1)
        self.FertztoWater_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.FertztoWater_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.FertztoWater_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.FertztoWater_DoubleSpinBox.setMinimum(1.0)
        self.FertztoWater_DoubleSpinBox.setSingleStep(0.01)
        self.FertztoWater_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.FertztoWater_DoubleSpinBox.setProperty("value", 1.0)
        self.FertztoWater_DoubleSpinBox.setObjectName("FertztoWater_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.FertztoWater_DoubleSpinBox, 3, 3, 1, 1)
        self.Fertz_Equals_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Fertz_Equals_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Fertz_Equals_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Fertz_Equals_label.setObjectName("Fertz_Equals_label")
        self.gridLayout_4.addWidget(self.Fertz_Equals_label, 3, 4, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 3, 7, 1, 1)
        self.Fertz_Amount_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Fertz_Amount_label.setObjectName("Fertz_Amount_label")
        self.gridLayout_4.addWidget(self.Fertz_Amount_label, 3, 0, 1, 1)
        self.TapSafetoWater_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.TapSafetoWater_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.TapSafetoWater_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TapSafetoWater_DoubleSpinBox.setMinimum(1.0)
        self.TapSafetoWater_DoubleSpinBox.setSingleStep(0.01)
        self.TapSafetoWater_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.TapSafetoWater_DoubleSpinBox.setProperty("value", 1.0)
        self.TapSafetoWater_DoubleSpinBox.setObjectName("TapSafetoWater_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.TapSafetoWater_DoubleSpinBox, 4, 3, 1, 1)
        self.TapSafe_to_water_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TapSafe_to_water_label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.TapSafe_to_water_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TapSafe_to_water_label.setObjectName("TapSafe_to_water_label")
        self.gridLayout_4.addWidget(self.TapSafe_to_water_label, 4, 2, 1, 1)
        self.Fertz_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.Fertz_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Fertz_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.Fertz_DoubleSpinBox.setMinimum(1.0)
        self.Fertz_DoubleSpinBox.setSingleStep(0.01)
        self.Fertz_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.Fertz_DoubleSpinBox.setProperty("value", 1.0)
        self.Fertz_DoubleSpinBox.setObjectName("Fertz_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.Fertz_DoubleSpinBox, 3, 1, 1, 1)
        self.Fertz_ml_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Fertz_ml_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Fertz_ml_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Fertz_ml_label.setObjectName("Fertz_ml_label")
        self.gridLayout_4.addWidget(self.Fertz_ml_label, 3, 6, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 1, 7, 1, 1)
        self.conditioner_outLcd = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.conditioner_outLcd.setMode(QtWidgets.QLCDNumber.Dec)
        self.conditioner_outLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.conditioner_outLcd.setObjectName("conditioner_outLcd")
        self.gridLayout_4.addWidget(self.conditioner_outLcd, 4, 5, 1, 1)
        self.C02_Amount_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.C02_Amount_label.setObjectName("C02_Amount_label")
        self.gridLayout_4.addWidget(self.C02_Amount_label, 1, 0, 1, 1)
        self.TapSafe_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.TapSafe_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.TapSafe_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TapSafe_DoubleSpinBox.setMinimum(1.0)
        self.TapSafe_DoubleSpinBox.setSingleStep(0.01)
        self.TapSafe_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.TapSafe_DoubleSpinBox.setProperty("value", 1.0)
        self.TapSafe_DoubleSpinBox.setObjectName("TapSafe_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.TapSafe_DoubleSpinBox, 4, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 4, 7, 1, 1)
        self.C02toWater_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.C02toWater_DoubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.C02toWater_DoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.C02toWater_DoubleSpinBox.setMinimum(1.0)
        self.C02toWater_DoubleSpinBox.setMaximum(999.99)
        self.C02toWater_DoubleSpinBox.setSingleStep(0.01)
        self.C02toWater_DoubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.C02toWater_DoubleSpinBox.setProperty("value", 1.0)
        self.C02toWater_DoubleSpinBox.setObjectName("C02toWater_DoubleSpinBox")
        self.gridLayout_4.addWidget(self.C02toWater_DoubleSpinBox, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 701, 331))
        self.groupBox_10.setAutoFillBackground(True)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_2 = QtWidgets.QLabel(self.groupBox_10)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_10)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 21))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 81, 21))
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 81, 21))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 79, 231, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 120, 181, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 160, 113, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 200, 131, 20))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 231, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 120, 31, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_10)
        self.label_7.setGeometry(QtCore.QRect(290, 110, 20, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setGeometry(QtCore.QRect(350, 40, 81, 21))
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setGeometry(QtCore.QRect(350, 80, 81, 21))
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 40, 231, 21))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_10)
        self.textEdit.setGeometry(QtCore.QRect(20, 240, 321, 71))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.pause_button = QtWidgets.QPushButton(self.groupBox_22)
        self.pause_button.setGeometry(QtCore.QRect(580, 380, 51, 23))
        self.pause_button.setObjectName("pause_button")
        self.clear_log_button = QtWidgets.QPushButton(self.groupBox_22)
        self.clear_log_button.setGeometry(QtCore.QRect(640, 380, 75, 23))
        self.clear_log_button.setObjectName("clear_log_button")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Aquarium Control"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textBrowser.setPlaceholderText(_translate("Form", "---Aquarium Monitoring---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Home"))
        self.Auto_Dosing_Options.setTitle(_translate("Form", "Auto_Dosing_Options"))
        self.feed_sec_label.setText(_translate("Form", "Seconds"))
        self.feed_next_dose_label.setText(_translate("Form", "Next Dose: HR:MM:SS"))
        self.feed_week_label.setText(_translate("Form", "times a day"))
        self.feed_comboBox_2.setItemText(0, _translate("Form", "1"))
        self.feed_comboBox_2.setItemText(1, _translate("Form", "2"))
        self.feed_comboBox_2.setItemText(2, _translate("Form", "3"))
        self.feed_comboBox_2.setItemText(3, _translate("Form", "4"))
        self.feed_pushButton.setText(_translate("Form", "Feed"))
        self.c02_comboBox_2.setItemText(0, _translate("Form", "1"))
        self.c02_comboBox_2.setItemText(1, _translate("Form", "2"))
        self.c02_comboBox_2.setItemText(2, _translate("Form", "3"))
        self.c02_comboBox_2.setItemText(3, _translate("Form", "4"))
        self.c02_pushButton.setText(_translate("Form", "CO2"))
        self.c02_week_label.setText(_translate("Form", "times a day"))
        self.c02_next_dose_label.setText(_translate("Form", "Next Dose: HR:MM:SS"))
        self.c02_ml_label.setText(_translate("Form", "ml"))
        self.c02_seconds_label_2.setText(_translate("Form", "Seconds"))
        self.fertz_ml_label.setText(_translate("Form", "ml"))
        self.fertz_comboBox_2.setItemText(0, _translate("Form", "1"))
        self.fertz_comboBox_2.setItemText(1, _translate("Form", "2"))
        self.fertz_comboBox_2.setItemText(2, _translate("Form", "3"))
        self.fertz_comboBox_2.setItemText(3, _translate("Form", "4"))
        self.fertz_comboBox_2.setItemText(4, _translate("Form", "5"))
        self.fertz_comboBox_2.setItemText(5, _translate("Form", "6"))
        self.fertz_comboBox_2.setItemText(6, _translate("Form", "7"))
        self.fertz_week_label.setText(_translate("Form", "times a week"))
        self.fertz_next_dose_label.setText(_translate("Form", "Next Dose: DD/HR:MM:SS"))
        self.fertz_pushButton.setText(_translate("Form", "Ferts"))
        self.tapSafe_pushButton.setText(_translate("Form", "Tap Safe"))
        self.tapSafe_ml_label.setText(_translate("Form", "ml"))
        self.water_conditioner_comboBox.setItemText(0, _translate("Form", "1"))
        self.water_conditioner_comboBox.setItemText(1, _translate("Form", "2"))
        self.water_conditioner_comboBox.setItemText(2, _translate("Form", "3"))
        self.water_conditioner_comboBox.setItemText(3, _translate("Form", "4"))
        self.water_conditioner_comboBox.setItemText(4, _translate("Form", "5"))
        self.water_conditioner_comboBox.setItemText(5, _translate("Form", "6"))
        self.water_conditioner_comboBox.setItemText(6, _translate("Form", "7"))
        self.tapSafe_week_label.setText(_translate("Form", "times a week"))
        self.tapSafe_next_dose_label.setText(_translate("Form", "Next Dose: DD/HR:MM:SS"))
        self.Auto_Dosing.setTitle(_translate("Form", "Auto_Dosing"))
        self.label_12.setText(_translate("Form", "P10(mL)"))
        self.c02_label.setText(_translate("Form", "C02"))
        self.FeedCalibrationButton.setText(_translate("Form", "Calibrate"))
        self.label_11.setText(_translate("Form", "Seconds"))
        self.feed_label.setText(_translate("Form", "Feed"))
        self.c02_comboBox.setItemText(0, _translate("Form", "Auto"))
        self.c02_comboBox.setItemText(1, _translate("Form", "Manual"))
        self.C02CalibrationButton.setText(_translate("Form", "Calibrate"))
        self.feed_comboBox.setItemText(0, _translate("Form", "Auto"))
        self.feed_comboBox.setItemText(1, _translate("Form", "Manual"))
        self.label_17.setText(_translate("Form", "Sec. P(mL)"))
        self.fertz_comboBox.setItemText(0, _translate("Form", "Auto"))
        self.fertz_comboBox.setItemText(1, _translate("Form", "Manual"))
        self.fertz_label.setText(_translate("Form", "Fertz"))
        self.tapSafe_comboBox.setItemText(0, _translate("Form", "Auto"))
        self.tapSafe_comboBox.setItemText(1, _translate("Form", "Manual"))
        self.TapSafeCalibrationButton.setText(_translate("Form", "Calibrate"))
        self.FertzCalibrationButton.setText(_translate("Form", "Calibrate"))
        self.tapSafe_label.setText(_translate("Form", "Tap Safe"))
        self.label_15.setText(_translate("Form", "Seconds"))
        self.label_16.setText(_translate("Form", "P10(mL)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dosing_tab), _translate("Form", "Dosing"))
        self.Light_Modes.setTitle(_translate("Form", "Light_Modes"))
        self.sunrise_sunset_radioButton.setText(_translate("Form", "Sunrise/Sunset"))
        self.manual_hour_mode_radioButton.setText(_translate("Form", "Auto Mode"))
        self.toggle_mode_radioButton.setText(_translate("Form", "Toggle Mode"))
        self.light_mode_comboBox.setItemText(0, _translate("Form", "Day"))
        self.light_mode_comboBox.setItemText(1, _translate("Form", "Night"))
        self.light_mode_comboBox.setItemText(2, _translate("Form", "Off"))
        self.Light_Modes_Manual_Hours.setTitle(_translate("Form", "Light Hours"))
        self.pushButton_7.setText(_translate("Form", "Save"))
        self.groupBox_21.setTitle(_translate("Form", "Off Hour"))
        self.groupBox_19.setTitle(_translate("Form", "Day Hour"))
        self.groupBox_20.setTitle(_translate("Form", "Night Hour"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home_tab), _translate("Form", "Light Control"))
        self.groupBox_26.setTitle(_translate("Form", "Hours"))
        self.hours_22.setText(_translate("Form", "22"))
        self.hours_21.setText(_translate("Form", "21"))
        self.hours_5.setText(_translate("Form", "5"))
        self.label_13.setText(_translate("Form", "AM:"))
        self.hours_0.setText(_translate("Form", "0"))
        self.hours_20.setText(_translate("Form", "20"))
        self.hours_1.setText(_translate("Form", "1"))
        self.hours_23.setText(_translate("Form", "23"))
        self.hours_14.setText(_translate("Form", "14"))
        self.label_14.setText(_translate("Form", "PM:"))
        self.hours_10.setText(_translate("Form", "10"))
        self.hours_18.setText(_translate("Form", "18"))
        self.hours_3.setText(_translate("Form", "3"))
        self.hours_16.setText(_translate("Form", "16"))
        self.hours_9.setText(_translate("Form", "9"))
        self.hours_7.setText(_translate("Form", "7"))
        self.hours_11.setText(_translate("Form", "11"))
        self.hours_13.setText(_translate("Form", "13"))
        self.hours_6.setText(_translate("Form", "6"))
        self.hours_12.setText(_translate("Form", "12"))
        self.hours_8.setText(_translate("Form", "8"))
        self.hours_2.setText(_translate("Form", "2"))
        self.hours_17.setText(_translate("Form", "17"))
        self.hours_15.setText(_translate("Form", "15"))
        self.hours_4.setText(_translate("Form", "4"))
        self.hours_19.setText(_translate("Form", "19"))
        self.hour_comboBox.setItemText(0, _translate("Form", "Day"))
        self.hour_comboBox.setItemText(1, _translate("Form", "Night"))
        self.hour_comboBox.setItemText(2, _translate("Form", "Off"))
        self.hour_clear.setText(_translate("Form", "Clear All"))
        self.hour_save_button.setText(_translate("Form", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Sch"))
        self.inlet_level_label.setText(_translate("Form", "Inlet Tank Level"))
        self.outlet_level_label.setText(_translate("Form", "Outlet Tank Level"))
        self.aquarium_level_label.setText(_translate("Form", "Aquarium Level"))
        self.water_cycle_button.setText(_translate("Form", "Auto Water Change"))
        self.percentage_of_tank_comboBox.setItemText(0, _translate("Form", "5%"))
        self.percentage_of_tank_comboBox.setItemText(1, _translate("Form", "10%"))
        self.percentage_of_tank_comboBox.setItemText(2, _translate("Form", "15%"))
        self.percentage_of_tank_comboBox.setItemText(3, _translate("Form", "20%"))
        self.percentage_of_tank_comboBox.setItemText(4, _translate("Form", "25%"))
        self.percentage_of_tank_comboBox.setItemText(5, _translate("Form", "33.33%"))
        self.comboBox_10.setItemText(0, _translate("Form", "Dose on Cycle"))
        self.comboBox_10.setItemText(1, _translate("Form", "Do Nothing On Cycle"))
        self.label_10.setText(_translate("Form", "Water Levels"))
        self.pushButton.setText(_translate("Form", "Inlet Tank Refilled"))
        self.pushButton_2.setText(_translate("Form", "Outlet Tank Emptied"))
        self.pump_in_button.setText(_translate("Form", "Pump In"))
        self.pump_out_button.setText(_translate("Form", "Pump Out"))
        self.pushButton_3.setText(_translate("Form", "Filter On"))
        self.pushButton_4.setText(_translate("Form", "Filter Off"))
        self.label_18.setText(_translate("Form", "High Temp. Alert"))
        self.label_20.setText(_translate("Form", "Low Temp. Alert"))
        self.degrees_c_label.setText(_translate("Form", "° C"))
        self.degrees_c_label_2.setText(_translate("Form", "° F"))
        self.label_19.setText(_translate("Form", "Tank Temperature"))
        self.degrees_c_label_3.setText(_translate("Form", "° C"))
        self.degrees_c_label_4.setText(_translate("Form", "° F"))
        self.label_21.setText(_translate("Form", "Room Temperature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Water Monitoring"))
        self.groupBox_7.setTitle(_translate("Form", "Calender"))
        self.groupBox_8.setTitle(_translate("Form", "Doses"))
        self.conditioner__sch_pushButton.setText(_translate("Form", "Water Cond."))
        self.repeat_comboBox.setItemText(0, _translate("Form", "Daily"))
        self.repeat_comboBox.setItemText(1, _translate("Form", "Weekly"))
        self.repeat_comboBox.setItemText(2, _translate("Form", "Fortnightly"))
        self.repeat_comboBox.setItemText(3, _translate("Form", "Monthly"))
        self.fertz_sch_pushButton.setText(_translate("Form", "Fertilizer"))
        self.co2_sch_pushButton.setText(_translate("Form", "Co2"))
        self.date_display_LineEdit.setText(_translate("Form", "Select a Date on the Calendar"))
        self.water_cycle_sch_pushButton.setText(_translate("Form", "Water Cycle"))
        self.label.setText(_translate("Form", "Repeat:"))
        self.del_events_pushButton.setText(_translate("Form", "Delete Events"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Schedule_tab), _translate("Form", "Schedule"))
        self.TapSafe_Amount_label.setText(_translate("Form", " Tap Safe Amount (mL)"))
        self.TapSafe_Equals_label.setText(_translate("Form", "="))
        self.C02_to_water_label.setText(_translate("Form", "To H20 (Ll)"))
        self.saveDoses_pushButton.setText(_translate("Form", "Save to Dosing"))
        self.TapSafe_ml_label.setText(_translate("Form", " (mL)"))
        self.TankSize_label.setText(_translate("Form", "Enter Tank Size (L)"))
        self.C02_ml_label.setText(_translate("Form", " (mL)"))
        self.TankReq_label.setText(_translate("Form", "Dosage to Apply"))
        self.C02_Equals_label.setText(_translate("Form", "="))
        self.Fertz_to_water_label.setText(_translate("Form", "To H20 (L)"))
        self.Fertz_Equals_label.setText(_translate("Form", "="))
        self.pushButton_9.setText(_translate("Form", "Reset"))
        self.Fertz_Amount_label.setText(_translate("Form", " Fertz Amount (mL)"))
        self.TapSafe_to_water_label.setText(_translate("Form", "To H20 (L)"))
        self.Fertz_ml_label.setText(_translate("Form", " (mL)"))
        self.pushButton_6.setText(_translate("Form", "Reset"))
        self.C02_Amount_label.setText(_translate("Form", " C02 Amount (mL)"))
        self.pushButton_10.setText(_translate("Form", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Fluid Conversions"))
        self.label_2.setText(_translate("Form", "SSID:"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.label_4.setText(_translate("Form", "IP Address:"))
        self.label_5.setText(_translate("Form", "Port:"))
        self.label_6.setText(_translate("Form", "External Login:"))
        self.lineEdit_5.setText(_translate("Form", "http://trippyt.hopto.org/"))
        self.label_7.setText(_translate("Form", "."))
        self.label_8.setText(_translate("Form", "Holiday Mode:"))
        self.label_9.setText(_translate("Form", "SSID:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Settings"))
        self.pause_button.setText(_translate("Form", "Pause"))
        self.clear_log_button.setText(_translate("Form", "Refresh Log"))
